# TalentMatcher Configuration Properties
clientId=talent-matcher-app-2026
geminiModel=gemini-1.5-flash
serverHost=127.0.0.1
serverPort=8000
memoryLimit=100
projectId=resumeanalyser-500018
projectNumber=126410730042
apiKey=
